ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - name: chartmuseum.51.250.41.10.sslip.io
      path: /
      tls: true
      tlsSecret: chartmuseum.51.250.41.10.sslip.io
