apiVersion: v1
kind: ConfigMap
metadata:
  name: mynginx
data:
  nginx.conf: |
    worker_processes  2;
    user              www-data;
    events {
      use           epoll;
      worker_connections  128;
    }
    error_log         /var/log/nginx/error.log info;
    http {
      server_tokens off;
      include       mime.types;
      charset       utf-8;
      access_log    /var/log/nginx/access.log  combined;
      server {
        server_name   localhost;
        listen        8080;
        error_page    500 502 503 504  /50x.html;
        location      / {
          root      /app/;
          autoindex on;
        }
        location = /basic_status {
          stub_status;
        }
      }
    }
