apiVersion: v1
kind: Service
metadata:
  name: mynginx-svc
  labels:
    app: mynginx

spec:
  selector:
    app: mynginx
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: web
      name: web
    - protocol: TCP
      port: 9113
      targetPort: metrics
      name: metrics
